import type { Product } from './types';

export const products: Product[] = [
  {
    id: 'silk-gown-noir',
    name: 'Silk Gown Noir',
    category: 'Women',
    subcategory: 'Dresses',
    price: 1290,
    description: 'A floor-length silk gown in deep noir, cut on the bias for a fluid silhouette that moves with the body.',
    details: ['100% mulberry silk', 'Bias-cut construction', 'Concealed back zip', 'Dry clean only', 'Made in Italy'],
    images: [
      'https://images.pexels.com/photos/9690414/pexels-photo-9690414.jpeg?auto=compress&cs=tinysrgb&h=1200&w=800',
      'https://images.pexels.com/photos/32619416/pexels-photo-32619416.jpeg?auto=compress&cs=tinysrgb&h=1200&w=800',
    ],
    colors: [
      { name: 'Noir', hex: '#0a0a0a' },
      { name: 'Ivory', hex: '#f5f0e8' },
    ],
    sizes: ['XS', 'S', 'M', 'L'],
    isBestseller: true,
    collection: 'Nocturne',
  },
  {
    id: 'satin-wrap-ambre',
    name: 'Satin Wrap Ambre',
    category: 'Women',
    subcategory: 'Dresses',
    price: 890,
    description: 'A luminous satin wrap dress in warm ambre, draping effortlessly from a structured shoulder.',
    details: ['Sandwashed satin', 'Adjustable wrap closure', 'Side seam pockets', 'Dry clean only', 'Made in France'],
    images: [
      'https://images.pexels.com/photos/34769660/pexels-photo-34769660.jpeg?auto=compress&cs=tinysrgb&h=1200&w=800',
      'https://images.pexels.com/photos/32628116/pexels-photo-32628116.jpeg?auto=compress&cs=tinysrgb&h=1200&w=800',
    ],
    colors: [
      { name: 'Ambre', hex: '#c8965a' },
      { name: 'Noir', hex: '#0a0a0a' },
    ],
    sizes: ['XS', 'S', 'M', 'L'],
    isNew: true,
    collection: 'Nocturne',
  },
  {
    id: 'tailored-blazer-ivory',
    name: 'Tailored Blazer Ivory',
    category: 'Women',
    subcategory: 'Outerwear',
    price: 1150,
    description: 'A sharply tailored double-breasted blazer in ivory wool, sculpted at the waist for architectural structure.',
    details: ['Italian virgin wool', 'Double-breasted, six-button', 'Bemberg cupro lining', 'Functional cuff buttons', 'Made in Italy'],
    images: [
      'https://images.pexels.com/photos/33717116/pexels-photo-33717116.jpeg?auto=compress&cs=tinysrgb&h=1200&w=800',
      'https://images.pexels.com/photos/7945666/pexels-photo-7945666.jpeg?auto=compress&cs=tinysrgb&h=1200&w=800',
    ],
    colors: [
      { name: 'Ivory', hex: '#f5f0e8' },
      { name: 'Noir', hex: '#0a0a0a' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    isBestseller: true,
    collection: 'Atelier',
  },
  {
    id: 'feathered-hat-noir',
    name: 'Feathered Hat Noir',
    category: 'Women',
    subcategory: 'Headwear',
    price: 650,
    description: 'A dramatic wide-brim hat in noir with hand-placed feather detail, a statement of quiet rebellion.',
    details: ['Wool felt body', 'Hand-applied feather trim', 'Adjustable inner band', 'Imported'],
    images: [
      'https://images.pexels.com/photos/39525295/pexels-photo-39525295.jpeg?auto=compress&cs=tinysrgb&h=1200&w=800',
      'https://images.pexels.com/photos/37618169/pexels-photo-37618169.jpeg?auto=compress&cs=tinysrgb&h=1200&w=800',
    ],
    colors: [
      { name: 'Noir', hex: '#0a0a0a' },
    ],
    sizes: ['One Size'],
    isNew: true,
    collection: 'Nocturne',
  },
  {
    id: 'monochrome-coat-blanc',
    name: 'Monochrome Coat Blanc',
    category: 'Women',
    subcategory: 'Outerwear',
    price: 1890,
    description: 'A sweeping monochrome coat in blanc, minimal in line and maximal in presence.',
    details: ['Wool-cashmere blend', 'Oversized cocoon silhouette', 'Hidden snap closure', 'Made in Italy'],
    images: [
      'https://images.pexels.com/photos/20837189/pexels-photo-20837189.jpeg?auto=compress&cs=tinysrgb&h=1200&w=800',
      'https://images.pexels.com/photos/37577195/pexels-photo-37577195.jpeg?auto=compress&cs=tinysrgb&h=1200&w=800',
    ],
    colors: [
      { name: 'Blanc', hex: '#f5f0e8' },
      { name: 'Noir', hex: '#0a0a0a' },
    ],
    sizes: ['XS', 'S', 'M', 'L'],
    collection: 'Atelier',
  },
  {
    id: 'studio-trouser-noir',
    name: 'Studio Trouser Noir',
    category: 'Women',
    subcategory: 'Trousers',
    price: 590,
    description: 'High-waisted wide-leg trousers in noir, cut from a structured wool blend with a fluid drape.',
    details: ['Wool-viscose blend', 'High-rise waist', 'Wide leg', 'Side zip closure', 'Made in Italy'],
    images: [
      'https://images.pexels.com/photos/15032793/pexels-photo-15032793.jpeg?auto=compress&cs=tinysrgb&h=1200&w=800',
      'https://images.pexels.com/photos/14408070/pexels-photo-14408070.jpeg?auto=compress&cs=tinysrgb&h=1200&w=800',
    ],
    colors: [
      { name: 'Noir', hex: '#0a0a0a' },
      { name: 'Ivory', hex: '#f5f0e8' },
    ],
    sizes: ['XS', 'S', 'M', 'L'],
    collection: 'Atelier',
  },
  {
    id: 'tailored-suit-charcoal',
    name: 'Tailored Suit Charcoal',
    category: 'Men',
    subcategory: 'Suits',
    price: 2490,
    description: 'A two-piece suit in charcoal with a slim, contemporary silhouette and half-canvas construction.',
    details: ['Super 120s wool', 'Half-canvas construction', 'Side-vented jacket', 'Tapered trouser', 'Made in Italy'],
    images: [
      'https://images.pexels.com/photos/38399171/pexels-photo-38399171.jpeg?auto=compress&cs=tinysrgb&h=1200&w=800',
      'https://images.pexels.com/photos/4651334/pexels-photo-4651334.jpeg?auto=compress&cs=tinysrgb&h=1200&w=800',
    ],
    colors: [
      { name: 'Charcoal', hex: '#3a3a3a' },
      { name: 'Noir', hex: '#0a0a0a' },
    ],
    sizes: ['46', '48', '50', '52', '54'],
    isBestseller: true,
    collection: 'Monsieur',
  },
  {
    id: 'double-breasted-suit-noir',
    name: 'Double-Breasted Suit Noir',
    category: 'Men',
    subcategory: 'Suits',
    price: 2690,
    description: 'A double-breasted noir suit with peak lapels, tailored for a sharp, architectural line.',
    details: ['Super 130s wool', 'Full-canvas construction', 'Peak lapel', 'Double-vented jacket', 'Made in Italy'],
    images: [
      'https://images.pexels.com/photos/4651342/pexels-photo-4651342.jpeg?auto=compress&cs=tinysrgb&h=1200&w=800',
      'https://images.pexels.com/photos/4651394/pexels-photo-4651394.jpeg?auto=compress&cs=tinysrgb&h=1200&w=800',
    ],
    colors: [
      { name: 'Noir', hex: '#0a0a0a' },
    ],
    sizes: ['46', '48', '50', '52'],
    isNew: true,
    collection: 'Monsieur',
  },
  {
    id: 'modern-blazer-slate',
    name: 'Modern Blazer Slate',
    category: 'Men',
    subcategory: 'Jackets',
    price: 1290,
    description: 'A versatile slate blazer with a soft shoulder and natural drape, bridging formal and casual.',
    details: ['Wool-silk blend', 'Unlined, soft shoulder', 'Patch pockets', 'Made in Italy'],
    images: [
      'https://images.pexels.com/photos/4651486/pexels-photo-4651486.jpeg?auto=compress&cs=tinysrgb&h=1200&w=800',
      'https://images.pexels.com/photos/32478285/pexels-photo-32478285.jpeg?auto=compress&cs=tinysrgb&h=1200&w=800',
    ],
    colors: [
      { name: 'Slate', hex: '#5a5a6a' },
      { name: 'Noir', hex: '#0a0a0a' },
    ],
    sizes: ['46', '48', '50', '52', '54'],
    collection: 'Monsieur',
  },
  {
    id: 'leather-handbag-camel',
    name: 'Leather Handbag Camel',
    category: 'Accessories',
    subcategory: 'Bags',
    price: 1490,
    description: 'A structured top-handle bag in camel leather with gold hardware and a removable shoulder strap.',
    details: ['Italian calf leather', 'Gold-tone hardware', 'Removable shoulder strap', 'Suede lining', 'Made in Italy'],
    images: [
      'https://images.pexels.com/photos/12194934/pexels-photo-12194934.jpeg?auto=compress&cs=tinysrgb&h=1200&w=800',
      'https://images.pexels.com/photos/37384060/pexels-photo-37384060.jpeg?auto=compress&cs=tinysrgb&h=1200&w=800',
    ],
    colors: [
      { name: 'Camel', hex: '#c8965a' },
      { name: 'Noir', hex: '#0a0a0a' },
    ],
    sizes: ['One Size'],
    isBestseller: true,
    collection: 'Atelier',
  },
  {
    id: 'chain-bag-ivoire',
    name: 'Chain Bag Ivoire',
    category: 'Accessories',
    subcategory: 'Bags',
    price: 1690,
    description: 'A quilted ivoire bag with a gold chain strap, blending vintage elegance with modern proportion.',
    details: ['Lambskin leather', 'Gold chain strap', 'Quilted pattern', 'Magnetic flap closure', 'Made in France'],
    images: [
      'https://images.pexels.com/photos/30748146/pexels-photo-30748146.jpeg?auto=compress&cs=tinysrgb&h=1200&w=800',
      'https://images.pexels.com/photos/8989582/pexels-photo-8989582.jpeg?auto=compress&cs=tinysrgb&h=1200&w=800',
    ],
    colors: [
      { name: 'Ivoire', hex: '#f5f0e8' },
      { name: 'Noir', hex: '#0a0a0a' },
    ],
    sizes: ['One Size'],
    isNew: true,
    collection: 'Nocturne',
  },
  {
    id: 'fur-coat-bordeaux',
    name: 'Fur Coat Bordeaux',
    category: 'Women',
    subcategory: 'Outerwear',
    price: 3200,
    description: 'A sumptuous faux fur coat in deep bordeaux, oversized and enveloping with a sculpted collar.',
    details: ['Modacrylic faux fur', 'Oversized fit', 'Hook-and-eye closure', 'Satin lining', 'Made in Italy'],
    images: [
      'https://images.pexels.com/photos/35733628/pexels-photo-35733628.jpeg?auto=compress&cs=tinysrgb&h=1200&w=800',
      'https://images.pexels.com/photos/34121564/pexels-photo-34121564.jpeg?auto=compress&cs=tinysrgb&h=1200&w=800',
    ],
    colors: [
      { name: 'Bordeaux', hex: '#6b2c2c' },
      { name: 'Noir', hex: '#0a0a0a' },
    ],
    sizes: ['S', 'M', 'L'],
    collection: 'Nocturne',
  },
];

export const collections = [
  {
    name: 'Nocturne',
    subtitle: 'Autumn / Winter 2026',
    description: 'After-dark elegance. Deep tones, fluid silhouettes, and a study in shadow.',
    image: 'https://images.pexels.com/photos/35730957/pexels-photo-35730957.jpeg?auto=compress&cs=tinysrgb&h=1000&w=800',
  },
  {
    name: 'Atelier',
    subtitle: 'The Essentials',
    description: 'Precision tailoring and timeless form. The foundation of the AURELLE wardrobe.',
    image: 'https://images.pexels.com/photos/5531709/pexels-photo-5531709.jpeg?auto=compress&cs=tinysrgb&h=1000&w=800',
  },
  {
    name: 'Monsieur',
    subtitle: 'Menswear Collection',
    description: 'Modern tailoring for the man who dresses with intent. Sharp lines, soft shoulders.',
    image: 'https://images.pexels.com/photos/4651334/pexels-photo-4651334.jpeg?auto=compress&cs=tinysrgb&h=1000&w=800',
  },
];

export const lookbookImages = [
  { url: 'https://images.pexels.com/photos/32443161/pexels-photo-32443161.jpeg?auto=compress&cs=tinysrgb&h=1400&w=900', caption: 'Nocturne I', category: 'Editorial' },
  { url: 'https://images.pexels.com/photos/38290951/pexels-photo-38290951.jpeg?auto=compress&cs=tinysrgb&h=1400&w=900', caption: 'Urban Monochrome', category: 'Editorial' },
  { url: 'https://images.pexels.com/photos/7453205/pexels-photo-7453205.jpeg?auto=compress&cs=tinysrgb&h=1400&w=900', caption: 'Riviera', category: 'Editorial' },
  { url: 'https://images.pexels.com/photos/39116875/pexels-photo-39116875.jpeg?auto=compress&cs=tinysrgb&h=1400&w=900', caption: 'Crimson Hour', category: 'Editorial' },
  { url: 'https://images.pexels.com/photos/29898864/pexels-photo-29898864.jpeg?auto=compress&cs=tinysrgb&h=1400&w=900', caption: 'Vintage Noir', category: 'Editorial' },
  { url: 'https://images.pexels.com/photos/7697685/pexels-photo-7697685.jpeg?auto=compress&cs=tinysrgb&h=1400&w=900', caption: 'Atelier Study', category: 'Editorial' },
];

export const heroImages = [
  'https://images.pexels.com/photos/32443161/pexels-photo-32443161.jpeg?auto=compress&cs=tinysrgb&h=1600&w=1080',
  'https://images.pexels.com/photos/9690414/pexels-photo-9690414.jpeg?auto=compress&cs=tinysrgb&h=1600&w=1080',
  'https://images.pexels.com/photos/35730957/pexels-photo-35730957.jpeg?auto=compress&cs=tinysrgb&h=1600&w=1080',
];
